name: pull_request-workflow
on: pull_request

jobs:
  pull_request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hi world
          echo hello world

